theme: jekyll-theme-leap-day
title: John Chesshir's Religious and Political Website
description: This is the start of what will be various political and religious topics that I often mull on during the day.
